version: '3.8'

services:
  psi-service:
    build:
      context: ./services/psi-service
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    volumes:
      - ./data/synth:/app/data/synth:ro
    environment:
      - PORT=7001
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - federated-net

  consent-service:
    build:
      context: ./services/consent-service
      dockerfile: Dockerfile
    ports:
      - "7002:7002"
    environment:
      - PORT=7002
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - federated-net

  train-service:
    build:
      context: ./services/train-service
      dockerfile: Dockerfile
    ports:
      - "7003:7003"
    volumes:
      - ./data/synth:/app/data/synth:ro
      - ./artifacts:/app/artifacts
    environment:
      - PORT=7003
      - LOG_LEVEL=INFO
      - PSI_SERVICE_URL=http://psi-service:7001
    depends_on:
      - psi-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7003/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - federated-net

  serving-service:
    build:
      context: ./services/serving-service
      dockerfile: Dockerfile
    ports:
      - "7004:7004"
    volumes:
      - ./artifacts:/app/artifacts:ro
      - ./data/synth:/app/data/synth:ro
    environment:
      - PORT=7004
      - LOG_LEVEL=INFO
      - CONSENT_SERVICE_URL=http://consent-service:7002
    depends_on:
      - consent-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7004/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - federated-net

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_PSI_SERVICE_URL=http://localhost:7001
      - VITE_CONSENT_SERVICE_URL=http://localhost:7002
      - VITE_TRAIN_SERVICE_URL=http://localhost:7003
      - VITE_SERVING_SERVICE_URL=http://localhost:7004
    depends_on:
      - psi-service
      - consent-service
      - train-service
      - serving-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - federated-net

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=federated_risk
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - federated-net

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - federated-net

volumes:
  artifacts:
  postgres_data:
  redis_data:

networks:
  federated-net:
    driver: bridge