apiVersion: v1
kind: Namespace
metadata:
  name: federated-risk
  labels:
    name: federated-risk
    app.kubernetes.io/name: federated-risk-demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: federated-risk-system
  annotations:
    description: "联邦风控系统演示环境命名空间"
    contact: "admin@federated-risk.com"
    created-by: "federated-risk-demo"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: federated-risk-quota
  namespace: federated-risk
spec:
  hard:
    # 计算资源限制
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # 存储资源限制
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # 对象数量限制
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
    deployments.apps: "15"
    statefulsets.apps: "5"
    jobs.batch: "10"
    cronjobs.batch: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: federated-risk-limits
  namespace: federated-risk
spec:
  limits:
  # Pod级别限制
  - type: Pod
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
  
  # Container级别限制
  - type: Container
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  
  # PVC级别限制
  - type: PersistentVolumeClaim
    max:
      storage: 50Gi
    min:
      storage: 1Gi